### ISSUE TITLE
Collecting custom metrics

### ISSUE THREAD

**Issue by Lisomatrix** [klaviyo/klaviyo-android-sdk#167]
### Checklist

- [X] I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-android-sdk/blob/master/.github/CONTRIBUTING.md)
- [X] I have determined whether this bug is also reproducible in a vanilla Android project
- [X] If possible, I've reproduced the issue using the `master` branch or latest release of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-android-sdk/issues) or [pull request](https://github.com/klaviyo/klaviyo-android-sdk/pulls).

### Description

```markdown
I'm unable to set properties on events from objects outside of the module.

On this example it works fine

val productName = "Shirt"

Event(EventMetric.VIEWED_PRODUCT)
  .setProperty(EventKey.CUSTOM("ProductName"), productName)

However if the value of the property comes from an object of another module.

Event(EventMetric.VIEWED_PRODUCT)
  .setProperty(EventKey.CUSTOM("ProductName"), product.itemName)

It will complain with the following message:

Smart cast to 'String' is impossible, because 'product.itemName' is a public API property declared in different module

Which is weird since product.itemName is of type String. However if I typecast into String it will work, even though IDE complains as "No cast needed".

Event(EventMetric.VIEWED_PRODUCT)
  .setProperty(EventKey.CUSTOM("ProductName"), product.itemName as String)
```

### Expected behavior

```markdown
To be able to collect set event properties of objects coming from another module.
```

### Actual behavior

```markdown
Smart cast to 'String' is impossible, because 'product.itemName' is a public API property declared in different module.
```

### Steps to reproduce

```markdown
1 - Create a Kotlin library module, in this case it was a Kotlin Multiplatform Module
2 - Create an class inside the module
3 - On the app module instantiate the class
4 - Create an event and set a property of the object
```

### The Klaviyo Android SDK version information

2.3.0

**Comment by evan-masseau** [comment]
Interesting, thanks for reporting this, and what your workaround was. We will dive into this and see if there's something we can fix.

**Comment by evan-masseau** [comment]
Hello again, from what I can tell reading up on this error message, this is out of our hands. Cross-module smart casting is prevented because the modules can re-compile independently so the compiler can't ensure the property's type won't change. I found this thread illuminating:

https://discuss.kotlinlang.org/t/what-is-the-reason-behind-smart-cast-being-impossible-to-perform-when-referenced-class-is-in-another-module/2201/46

On the plus side, as you referenced, there's an easy enough work around. It is unfortunate, considering the prevalence of java/android projects extracting data classes/models into a separate module.
